### ISSUE TITLE
Suggestion: Add parameters for known Pt genome and nuclear genome, to simplify the Mt genome

### ISSUE THREAD

**Issue by chenzixi07** [hwc2021/GSAT#12]
Dr. He,
I have a little suggestion. In the species I study, the Pt genome and nuclear genome is already reported.

So is it possible to use these known genomes to simplify the Mt genome assembly?

Regards,
Zixi Chen

**Comment by hwc2021** [comment]
Hi Zixi,

Thank you for your valuable advice. At least the Pt genome sequence is helpful for simplifying the assembly of the Mt genome. I will consider the possibility of adding such parameters in a later version.

Best,
Wenchuang
