### ISSUE TITLE
Suggestion：add -cpu parameters for graphLong

### ISSUE THREAD

**Issue by chenzixi07** [hwc2021/GSAT#13]
Dr. He,
I found that the first step have the -cpu parameter, but not for the second graphLong step.
However, blast/minimap2 all have parameters for multi-core, so it will be better to have a parameter for the users to control it.

Regards, 
Zixi Chen

**Comment by hwc2021** [comment]
Hi Zixi,

This is a very good suggestion. I will consider adding such parameters in a later version. Thank you very much!

Best,
Wenchuang

**Comment by hwc2021** [comment]
Hi Zixi,

This is a very good suggestion. I will consider adding such parameters in a later version. Thank you very much!

Best,
Wenchuang
