### ISSUE TITLE
Error in graphShort session

### ISSUE THREAD

**Issue by zhengyanstu** [hwc2021/GSAT#9]
Dear developers,

During the "gsat graphShort -conf example.conf" session, I encountered an issue where gsat failed to determine the offset and requested manual specification before restarting. Additionally, an error message was displayed, which read "== Error == system call for: "['/home/zzy/miniconda3/envs/rna/share/spades-3.13.0-0/bin/spades-hammer', '/run/media/zzy/Elements/kiwifruit_genome/white/gsat/spades/corrected/configs/config.info']" finished abnormally, err code: 255."

I am seeking assistance in understanding the cause of this error. I have attached the log file for reference.

Looking forward to your reply.
[spades.log](https://github.com/hwc2021/GSAT/files/13037381/spades.log)

**Comment by hwc2021** [comment]
Hello,

It seems that this error was reported by the spades software and could be caused by the quality of the sequencing reads you used.

You can try to conduct a quality control of the Illumina reads before they are used for GSAT.

**Comment by hwc2021** [comment]
Hello,

It seems that this error was reported by the spades software and could be caused by problems in the sequencing reads you used.

You can try to conduct a quality control of the Illumina reads before they are used for GSAT.

**Comment by zhengyanstu** [comment]
> Hello,
> 
> It seems that this error was reported by the spades software and could be caused by problems in the sequencing reads you used.
> 
> You can try to conduct a quality control of the Illumina reads before they are used for GSAT.

Thank you for your answer, I will try to polish that.
